# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitledJXkPcu.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QPushButton, QRadioButton,
    QSizePolicy, QSpinBox, QStatusBar, QWidget)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        if not mainWindow.objectName():
            mainWindow.setObjectName(u"mainWindow")
        mainWindow.resize(427, 586)
        self.actionopen = QAction(mainWindow)
        self.actionopen.setObjectName(u"actionopen")
        self.action = QAction(mainWindow)
        self.action.setObjectName(u"action")
        self.centralwidget = QWidget(mainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.TitleLabel1 = QLabel(self.centralwidget)
        self.TitleLabel1.setObjectName(u"TitleLabel1")
        self.TitleLabel1.setGeometry(QRect(0, 0, 391, 41))
        font = QFont()
        font.setFamilies([u"\ub9d1\uc740 \uace0\ub515 Semilight"])
        font.setPointSize(28)
        self.TitleLabel1.setFont(font)
        self.Pendulum1Label = QLabel(self.centralwidget)
        self.Pendulum1Label.setObjectName(u"Pendulum1Label")
        self.Pendulum1Label.setGeometry(QRect(0, 60, 111, 31))
        font1 = QFont()
        font1.setFamilies([u"\ub9d1\uc740 \uace0\ub515 Semilight"])
        font1.setPointSize(14)
        self.Pendulum1Label.setFont(font1)
        self.Pendulum1Label.setTextFormat(Qt.TextFormat.AutoText)
        self.Pendulum1Label.setMargin(3)
        self.LabelP1_1 = QLabel(self.centralwidget)
        self.LabelP1_1.setObjectName(u"LabelP1_1")
        self.LabelP1_1.setGeometry(QRect(10, 100, 31, 16))
        font2 = QFont()
        font2.setFamilies([u"\ub9d1\uc740 \uace0\ub515 Semilight"])
        self.LabelP1_1.setFont(font2)
        self.LabelP1_2 = QLabel(self.centralwidget)
        self.LabelP1_2.setObjectName(u"LabelP1_2")
        self.LabelP1_2.setGeometry(QRect(190, 100, 41, 16))
        self.LabelP1_2.setFont(font2)
        self.LabelP1_3 = QLabel(self.centralwidget)
        self.LabelP1_3.setObjectName(u"LabelP1_3")
        self.LabelP1_3.setGeometry(QRect(0, 140, 41, 16))
        self.LabelP1_3.setFont(font2)
        self.LabelP1_4 = QLabel(self.centralwidget)
        self.LabelP1_4.setObjectName(u"LabelP1_4")
        self.LabelP1_4.setGeometry(QRect(190, 140, 41, 16))
        self.LabelP1_4.setFont(font2)
        self.Pendulum2Label = QLabel(self.centralwidget)
        self.Pendulum2Label.setObjectName(u"Pendulum2Label")
        self.Pendulum2Label.setGeometry(QRect(0, 180, 111, 31))
        self.Pendulum2Label.setFont(font1)
        self.Pendulum2Label.setMargin(3)
        self.LabelP2_1 = QLabel(self.centralwidget)
        self.LabelP2_1.setObjectName(u"LabelP2_1")
        self.LabelP2_1.setGeometry(QRect(10, 220, 31, 16))
        self.LabelP2_1.setFont(font2)
        self.LabelP2_2 = QLabel(self.centralwidget)
        self.LabelP2_2.setObjectName(u"LabelP2_2")
        self.LabelP2_2.setGeometry(QRect(190, 220, 41, 16))
        self.LabelP2_2.setFont(font2)
        self.LabelP2_3 = QLabel(self.centralwidget)
        self.LabelP2_3.setObjectName(u"LabelP2_3")
        self.LabelP2_3.setGeometry(QRect(0, 260, 41, 16))
        self.LabelP2_3.setFont(font2)
        self.LabelP2_4 = QLabel(self.centralwidget)
        self.LabelP2_4.setObjectName(u"LabelP2_4")
        self.LabelP2_4.setGeometry(QRect(190, 260, 41, 16))
        self.LabelP2_4.setFont(font2)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 460, 411, 61))
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(u"QPushButton {\n"
"    background-color: rgb(0, 170, 0);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(85, 170, 0);\n"
"}")
        self.pushButton.setAutoDefault(False)
        self.notice = QLabel(self.centralwidget)
        self.notice.setObjectName(u"notice")
        self.notice.setGeometry(QRect(10, 390, 50, 16))
        self.notice.setFont(font2)
        self.notice_2 = QLabel(self.centralwidget)
        self.notice_2.setObjectName(u"notice_2")
        self.notice_2.setGeometry(QRect(20, 410, 311, 16))
        self.notice_2.setFont(font2)
        self.notice_3 = QLabel(self.centralwidget)
        self.notice_3.setObjectName(u"notice_3")
        self.notice_3.setGeometry(QRect(20, 430, 401, 16))
        self.notice_3.setFont(font2)
        self.p1_mass = QLineEdit(self.centralwidget)
        self.p1_mass.setObjectName(u"p1_mass")
        self.p1_mass.setGeometry(QRect(40, 100, 113, 26))
        self.p1_line = QLineEdit(self.centralwidget)
        self.p1_line.setObjectName(u"p1_line")
        self.p1_line.setGeometry(QRect(240, 100, 113, 26))
        self.p1_theta0 = QLineEdit(self.centralwidget)
        self.p1_theta0.setObjectName(u"p1_theta0")
        self.p1_theta0.setGeometry(QRect(40, 140, 113, 26))
        self.p1_omega0 = QLineEdit(self.centralwidget)
        self.p1_omega0.setObjectName(u"p1_omega0")
        self.p1_omega0.setGeometry(QRect(240, 140, 113, 26))
        self.p2_mass = QLineEdit(self.centralwidget)
        self.p2_mass.setObjectName(u"p2_mass")
        self.p2_mass.setGeometry(QRect(40, 220, 113, 26))
        self.p2_line = QLineEdit(self.centralwidget)
        self.p2_line.setObjectName(u"p2_line")
        self.p2_line.setGeometry(QRect(240, 220, 113, 26))
        self.p2_theta0 = QLineEdit(self.centralwidget)
        self.p2_theta0.setObjectName(u"p2_theta0")
        self.p2_theta0.setGeometry(QRect(40, 260, 113, 26))
        self.p2_omega0 = QLineEdit(self.centralwidget)
        self.p2_omega0.setObjectName(u"p2_omega0")
        self.p2_omega0.setGeometry(QRect(240, 260, 113, 26))
        self.PublicLabel = QLabel(self.centralwidget)
        self.PublicLabel.setObjectName(u"PublicLabel")
        self.PublicLabel.setGeometry(QRect(0, 300, 61, 31))
        self.PublicLabel.setFont(font1)
        self.PublicLabel.setMargin(3)
        self.Public_FrameAmount = QSpinBox(self.centralwidget)
        self.Public_FrameAmount.setObjectName(u"Public_FrameAmount")
        self.Public_FrameAmount.setGeometry(QRect(60, 340, 81, 26))
        self.Public_FrameAmount.setMinimum(50)
        self.Public_FrameAmount.setMaximum(1000)
        self.PublicLabel_2 = QLabel(self.centralwidget)
        self.PublicLabel_2.setObjectName(u"PublicLabel_2")
        self.PublicLabel_2.setGeometry(QRect(10, 330, 41, 21))
        self.PublicLabel_2.setFont(font2)
        self.PublicLabel_3 = QLabel(self.centralwidget)
        self.PublicLabel_3.setObjectName(u"PublicLabel_3")
        self.PublicLabel_3.setGeometry(QRect(0, 350, 61, 16))
        self.PublicLabel_3.setFont(font2)
        self.RadiobuttonFrame = QWidget(self.centralwidget)
        self.RadiobuttonFrame.setObjectName(u"RadiobuttonFrame")
        self.RadiobuttonFrame.setGeometry(QRect(150, 310, 131, 71))
        self.radioButton = QRadioButton(self.RadiobuttonFrame)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(10, 10, 121, 24))
        self.radioButton_2 = QRadioButton(self.RadiobuttonFrame)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(10, 30, 121, 24))
        self.radioButton_3 = QRadioButton(self.RadiobuttonFrame)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setGeometry(QRect(10, 50, 121, 24))
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(mainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 427, 33))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(mainWindow)
        self.statusbar.setObjectName(u"statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu.menuAction())
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.action)

        self.retranslateUi(mainWindow)

        QMetaObject.connectSlotsByName(mainWindow)
    # setupUi

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QCoreApplication.translate("mainWindow", u"Double Pendulum Simulator", None))
        self.actionopen.setText(QCoreApplication.translate("mainWindow", u"\uc5f4\uae30", None))
        self.action.setText(QCoreApplication.translate("mainWindow", u"\uc800\uc7a5", None))
        self.TitleLabel1.setText(QCoreApplication.translate("mainWindow", u"Pendullema", None))
        self.Pendulum1Label.setText(QCoreApplication.translate("mainWindow", u"Pendulum 1", None))
        self.LabelP1_1.setText(QCoreApplication.translate("mainWindow", u"\uc9c8\ub7c9", None))
        self.LabelP1_2.setText(QCoreApplication.translate("mainWindow", u"\uc904 \uae38\uc774", None))
        self.LabelP1_3.setText(QCoreApplication.translate("mainWindow", u"\ucd08\uae30\uac01", None))
        self.LabelP1_4.setText(QCoreApplication.translate("mainWindow", u"\uac01\uc18d\ub3c4", None))
        self.Pendulum2Label.setText(QCoreApplication.translate("mainWindow", u"Pendulum 2", None))
        self.LabelP2_1.setText(QCoreApplication.translate("mainWindow", u"\uc9c8\ub7c9", None))
        self.LabelP2_2.setText(QCoreApplication.translate("mainWindow", u"\uc904 \uae38\uc774", None))
        self.LabelP2_3.setText(QCoreApplication.translate("mainWindow", u"\ucd08\uae30\uac01", None))
        self.LabelP2_4.setText(QCoreApplication.translate("mainWindow", u"\uac01\uc18d\ub3c4", None))
        self.pushButton.setText(QCoreApplication.translate("mainWindow", u"\uc2dc\ubbac\ub808\uc774\uc158 \uc2e4\ud589", None))
        self.notice.setText(QCoreApplication.translate("mainWindow", u"\ucc38\uace0)", None))
        self.notice_2.setText(QCoreApplication.translate("mainWindow", u"\ubcf8 \ud504\ub85c\uadf8\ub7a8\uc740 SI \ub2e8\uc704\uacc4\ub97c \uc0ac\uc6a9\ud558\uace0 \uc788\uc2b5\ub2c8\ub2e4.", None))
        self.notice_3.setText(QCoreApplication.translate("mainWindow", u"\uac01\ub3c4\ub294 Rad\uc774\uba70, \uae30\uc900\uc120 \uae30\uc900 \uc624\ub978\ucabd\uc774 \uc591, \uc67c\ucabd\uc774 \uc74c\uc5d0 \ud574\ub2f9\ub429\ub2c8\ub2e4.", None))
        self.PublicLabel.setText(QCoreApplication.translate("mainWindow", u"Public", None))
        self.PublicLabel_2.setText(QCoreApplication.translate("mainWindow", u"\uc7a5\uba74 \ub2f9", None))
        self.PublicLabel_3.setText(QCoreApplication.translate("mainWindow", u"\ud504\ub808\uc784 \uc218", None))
        self.radioButton.setText(QCoreApplication.translate("mainWindow", u"CSV\ub85c \ub0b4\ubcf4\ub0b4\uae30", None))
        self.radioButton_2.setText(QCoreApplication.translate("mainWindow", u"Excel\ub85c \ub0b4\ubcf4\ub0b4\uae30", None))
        self.radioButton_3.setText(QCoreApplication.translate("mainWindow", u"\ub0b4\ubcf4\ub0b4\uc9c0 \uc54a\uc74c", None))
        self.menu.setTitle(QCoreApplication.translate("mainWindow", u"\ud30c\uc77c", None))
    # retranslateUi

